export const W=56,H=36,DEPTHS=5;
export const NAMES=['Town of Stonehaven','The Forgotten Halls','The Sunken Vaults','The Iron Warrens','The Ashen Deep','The Balrog’s Keep'];
export type Player={id:string;name:string;role:string;x:number;y:number;floor:number;hp:number;maxHp:number;mp:number;maxMp:number;level:number;xp:number;gold:number;potions:number;weapon:number;armor:number;seen:Record<string,number[]>;last:number;moveAt:number;attackAt:number;chatAt:number;ids:string[];log:string[];kills:number;wins:number};
export type Monster={id:string;name:string;glyph:string;color:string;x:number;y:number;hp:number;maxHp:number;power:number;homeX:number;homeY:number;deadAt:number;boss:boolean};
export type Floor={tiles:string[];up:{x:number;y:number};down:{x:number;y:number};monsters:Monster[];loot:{id:string;x:number;y:number;kind:string;value:number;goneAt:number}[]};
export type World={floors:Floor[];players:Record<string,Player>;chat:{name:string;text:string;at:number}[];tickAt:number;regenAt:number;createdAt:number};
export type Action={type:string;dx?:number;dy?:number;name?:string;role?:string;text?:string;item?:string;id?:string};
function rng(seed:number){return ()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y));
export function makeFloor(depth:number):Floor{
 const rand=rng(51821+depth*9049),grid=Array.from({length:H},()=>Array(W).fill('#'));
 const carve=(x:number,y:number,w:number,h:number)=>{for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)grid[j][i]='.';};
 const centers:{x:number;y:number}[]=[];
 if(!depth){carve(10,7,36,23);centers.push({x:27,y:24},{x:27,y:10});for(const [x,y] of [[14,11],[35,11],[14,23],[35,23]]){carve(x,y,7,5);for(let i=x;i<x+7;i++)grid[y][i]='#';grid[y+2][x+3]='S';}grid[25][27]='+';}
 else{for(let row=0;row<3;row++)for(let col=0;col<4;col++){const x=2+col*13+Math.floor(rand()*3),y=2+row*11+Math.floor(rand()*2),w=7+Math.floor(rand()*3),h=6+Math.floor(rand()*3);carve(x,y,w,h);centers.push({x:x+Math.floor(w/2),y:y+Math.floor(h/2)});}for(let i=1;i<centers.length;i++){const a=centers[i-1],b=centers[i];for(let x=Math.min(a.x,b.x);x<=Math.max(a.x,b.x);x++)grid[a.y][x]='.';for(let y=Math.min(a.y,b.y);y<=Math.max(a.y,b.y);y++)grid[y][b.x]='.';}}
 const up=centers[0],down=centers.at(-1)!;grid[up.y][up.x]=depth?'<':'.';grid[down.y][down.x]=depth<DEPTHS?'>':'*';
 const bestiary=[['Cave rat','r','#c7b292'],['Kobold','k','#a2bd72'],['Goblin','g','#6dcc8c'],['Orc','o','#dbb165'],['Troll','T','#cd9365'],['Wraith','W','#a797d9']];
 const monsters:Monster[]=[],loot:Floor['loot']=[];
 if(depth)for(let i=1;i<centers.length;i++){const c=centers[i],b=bestiary[Math.min(5,depth-1+(i%2))],hp=12+depth*10;monsters.push({id:`${depth}-m${i}`,name:b[0],glyph:b[1],color:b[2],x:c.x,y:c.y,hp,maxHp:hp,power:depth+2,homeX:c.x,homeY:c.y,deadAt:0,boss:false});loot.push({id:`${depth}-l${i}`,x:c.x-2,y:c.y,kind:i%3===0?'potion':'gold',value:10+depth*10,goneAt:0});}
 if(depth===DEPTHS){const m=monsters.at(-1)!;Object.assign(m,{name:'The Balrog',glyph:'B',color:'#ff754f',hp:360,maxHp:360,power:14,boss:true});}
 return {tiles:grid.map(r=>r.join('')),up,down,monsters,loot};
}
export function createWorld(now:number):World{return {floors:Array.from({length:DEPTHS+1},(_,i)=>makeFloor(i)),players:{},chat:[],tickAt:now,regenAt:now,createdAt:now};}
function log(p:Player,text:string){p.log=[...p.log.slice(-11),text];}
function alive(w:World,now:number){return Object.values(w.players).filter(p=>p.last>now-15000);}
export function canWalk(f:Floor,x:number,y:number){return x>=0&&y>=0&&x<W&&y<H&&f.tiles[y][x]!=='#';}
export function sight(f:Floor,a:{x:number;y:number},b:{x:number;y:number}){let x=a.x,y=a.y;const dx=Math.abs(b.x-x),sx=x<b.x?1:-1,dy=-Math.abs(b.y-y),sy=y<b.y?1:-1;let err=dx+dy;for(let i=0;i<100;i++){if(x===b.x&&y===b.y)return true;if((x!==a.x||y!==a.y)&&f.tiles[y]?.[x]==='#')return false;const e=2*err;if(e>=dy){err+=dy;x+=sx;}if(e<=dx){err+=dx;y+=sy;}}return false;}
function die(p:Player,w:World){p.gold=Math.floor(p.gold*.8);p.floor=0;p.x=w.floors[0].up.x;p.y=w.floors[0].up.y;p.hp=p.maxHp;p.mp=p.maxMp;log(p,'You fall. The town healer revives you; 20% of your gold is lost.');}
function hurt(w:World,p:Player,m:Monster,damage:number,now:number){m.hp-=damage;log(p,`You hit ${m.name} for ${damage}.`);if(m.hp<=0){m.hp=0;m.deadAt=now;p.gold+=m.boss?500:12+p.floor*8;p.kills++;const xp=m.boss?500:15+p.floor*12;const nearby=alive(w,now).filter(q=>q.floor===p.floor&&dist(q,m)<=8);for(const q of nearby){q.xp+=xp;log(q,`${m.name} slain. +${xp} XP.`);while(q.xp>=q.level*70){q.xp-=q.level*70;q.level++;q.maxHp+=10;q.maxMp+=3;q.hp=q.maxHp;q.mp=q.maxMp;log(q,`You reached level ${q.level}!`);}if(m.boss){q.wins++;log(q,'The Balrog has fallen. You are a conqueror of the deep!');}}}}
export function tick(w:World,now:number){const online=alive(w,now);if(now-w.tickAt>=650){w.tickAt=now;for(let d=1;d<=DEPTHS;d++){const f=w.floors[d],targets=online.filter(p=>p.floor===d);for(const m of f.monsters){if(m.hp<=0){if(now-m.deadAt>90000&&!targets.some(p=>dist(p,m)<9)){m.hp=m.maxHp;m.x=m.homeX;m.y=m.homeY;}continue;}const p=targets.filter(p=>dist(p,m)<=9&&sight(f,m,p)).sort((a,b)=>dist(a,m)-dist(b,m))[0];if(!p)continue;if(dist(p,m)<=1){p.hp-=Math.max(1,m.power-p.armor);log(p,`${m.name} hits you for ${Math.max(1,m.power-p.armor)}.`);if(p.hp<=0)die(p,w);}else{const dx=Math.sign(p.x-m.x),dy=Math.sign(p.y-m.y);for(const [sx,sy] of [[dx,0],[0,dy]]){if((sx||sy)&&canWalk(f,m.x+sx,m.y+sy)&&!f.monsters.some(n=>n!==m&&n.hp>0&&n.x===m.x+sx&&n.y===m.y+sy)){m.x+=sx;m.y+=sy;break;}}}}for(const l of f.loot)if(l.goneAt&&now-l.goneAt>120000)l.goneAt=0;}}
 if(now-w.regenAt>=2500){w.regenAt=now;for(const p of online){p.mp=Math.min(p.maxMp,p.mp+1);if(p.floor===0)p.hp=Math.min(p.maxHp,p.hp+6);}}
}
export function apply(w:World,key:string,a:Action,now:number){let p=w.players[key];
 if(a.type==='join'&&!p){const name=String(a.name||'').trim().replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,18);if(name.length<2)throw Error('Choose a name of at least 2 characters.');if(alive(w,now).length>=64)throw Error('This realm is full. Try again in a moment.');if(Object.keys(w.players).length>=1000)throw Error('This realm has reached its character limit.');const role=['Warrior','Mage','Ranger'].includes(a.role||'')?a.role!:'Warrior',maxHp=role==='Warrior'?70:role==='Mage'?42:55,maxMp=role==='Mage'?35:15;
 p=w.players[key]={id:crypto.randomUUID(),name,role,x:w.floors[0].up.x,y:w.floors[0].up.y,floor:0,hp:maxHp,maxHp,mp:maxMp,maxMp,level:1,xp:0,gold:25,potions:3,weapon:0,armor:0,seen:{},last:now,moveAt:0,attackAt:0,chatAt:0,ids:[],log:['Welcome to Stonehaven. Walk north to the > stairs; press E to descend.'],kills:0,wins:0};w.chat.push({name:'Realm',text:`${name} has arrived in Stonehaven.`,at:now});}
 if(!p)return null;
 if(a.type==='leave'){p.last=0;return p;}
 if(p.last<now-15000&&alive(w,now).length>=64)throw Error('This realm is full. Try again later.');
 p.last=now;
 if(a.id&&p.ids.includes(a.id))return p;
 if(a.id){p.ids.push(a.id);p.ids=p.ids.slice(-24);}
 const f=w.floors[p.floor];
 if(a.type==='move'&&now-p.moveAt>=150){const dx=Number(a.dx),dy=Number(a.dy);if(!Number.isInteger(dx)||!Number.isInteger(dy)||Math.abs(dx)+Math.abs(dy)!==1)return p;p.moveAt=now;const x=p.x+dx,y=p.y+dy;if(canWalk(f,x,y)){const m=f.monsters.find(m=>m.hp>0&&m.x===x&&m.y===y);if(m){if(now-p.attackAt>=450){p.attackAt=now;hurt(w,p,m,5+p.level*2+p.weapon*3+(p.role==='Warrior'?3:0),now);}}else{p.x=x;p.y=y;for(const l of f.loot)if(!l.goneAt&&l.x===x&&l.y===y){l.goneAt=now;if(l.kind==='potion'){p.potions++;log(p,'You found a healing potion.');}else{p.gold+=l.value;log(p,`You found ${l.value} gold.`);}}}}}
 if((a.type==='attack'||a.type==='spell')&&now-p.attackAt>=450){const spell=a.type==='spell',range=spell?6:p.role==='Ranger'?4:1;const target=f.monsters.filter(m=>m.hp>0&&dist(p,m)<=range&&sight(f,p,m)).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(!target)log(p,'No enemy in range.');else if(spell&&p.mp<5)log(p,'Not enough mana.');else{p.attackAt=now;if(spell)p.mp-=5;hurt(w,p,target,spell?12+p.level*3+(p.role==='Mage'?8:0):5+p.level*2+p.weapon*3+(p.role==='Warrior'?3:0),now);}}
 if(a.type==='potion'){if(p.potions&&p.hp<p.maxHp){p.potions--;p.hp=Math.min(p.maxHp,p.hp+40);log(p,'You drink a healing potion. +40 health.');}else log(p,p.potions?'You are already at full health.':'No potions remaining.');}
 if(a.type==='stairs'){const t=f.tiles[p.y][p.x];if(t==='>'||t==='<'){p.floor+=t==='>'?1:-1;const target=t==='>'?w.floors[p.floor].up:w.floors[p.floor].down;p.x=target.x;p.y=target.y;log(p,`You enter ${NAMES[p.floor]}.`);}else log(p,'Stand on < or > stairs, then press E.');}
 if(a.type==='recall'){if(p.floor===0)log(p,'You are already in town.');else if(p.gold<10)log(p,'Recall costs 10 gold.');else{p.gold-=10;p.floor=0;p.x=w.floors[0].up.x;p.y=w.floors[0].up.y;log(p,'You recall to Stonehaven. −10 gold.');}}
 if(a.type==='buy'){if(p.floor!==0)log(p,'The trader is in Stonehaven. Recall to town first.');else{const item=a.item,cost=item==='potion'?20:item==='weapon'?60*(p.weapon+1):item==='armor'?50*(p.armor+1):Infinity;if(p.gold<cost)log(p,'Not enough gold.');else{p.gold-=cost;if(item==='potion')p.potions++;if(item==='weapon')p.weapon++;if(item==='armor')p.armor++;log(p,`Purchased ${item}.`);}}}
 if(a.type==='chat'&&now-p.chatAt>=1500){const text=String(a.text||'').trim().slice(0,160);if(text){p.chatAt=now;w.chat.push({name:p.name,text,at:now});}}
 w.chat=w.chat.slice(-35);return p;
}
export function view(w:World,key:string,now:number){const p=w.players[key];if(!p)return {joined:false,online:alive(w,now).length};const f=w.floors[p.floor],seen=new Set(p.seen[p.floor]||[]),visible=new Set<number>();for(let y=Math.max(0,p.y-9);y<=Math.min(H-1,p.y+9);y++)for(let x=Math.max(0,p.x-11);x<=Math.min(W-1,p.x+11);x++)if(Math.hypot(x-p.x,y-p.y)<=11&&sight(f,p,{x,y})){visible.add(y*W+x);seen.add(y*W+x);}p.seen[p.floor]=[...seen];const {ids,last,moveAt,attackAt,chatAt,seen:history,...me}=p;return {joined:true,me,name:NAMES[p.floor],online:alive(w,now).length,tiles:f.tiles.map((row,y)=>row.split('').map((c,x)=>seen.has(y*W+x)?c:' ').join('')),visible:[...visible],monsters:f.monsters.filter(m=>m.hp>0&&visible.has(m.y*W+m.x)).map(({homeX,homeY,deadAt,...m})=>m),loot:f.loot.filter(l=>!l.goneAt&&visible.has(l.y*W+l.x)),players:alive(w,now).filter(q=>q.id!==p.id&&q.floor===p.floor&&visible.has(q.y*W+q.x)).map(q=>({id:q.id,name:q.name,role:q.role,x:q.x,y:q.y,hp:q.hp,maxHp:q.maxHp,level:q.level})),roster:alive(w,now).map(q=>({id:q.id,name:q.name,role:q.role,level:q.level,floor:q.floor})),chat:w.chat.slice(-18),serverTime:now};}
