'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Sword,Flame,FlaskConical,ArrowDownToLine,ScrollText,Users,Backpack,Volume2,VolumeX,Maximize2,HelpCircle,LogOut,Coins,Shield,ChevronUp,ChevronDown,ChevronLeft,ChevronRight} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {makeFloor,W,H,type Action,type Player,type Monster} from '@/lib/game';
type Snapshot={joined:boolean;online:number;me?:Omit<Player,'seen'|'ids'>;name?:string;tiles?:string[];visible?:number[];monsters?:Monster[];loot?:{x:number;y:number;kind:string}[];players?:{id:string;name:string;x:number;y:number;hp:number;maxHp:number;level:number}[];roster?:{id:string;name:string;role:string;level:number;floor:number}[];chat?:{name:string;text:string;at:number}[]};
const town=makeFloor(0);
const classInfo={Warrior:{glyph:'@',detail:'70 health · powerful melee',description:'Steel, endurance, and a place on the front line.'},Mage:{glyph:'✦',detail:'35 mana · empowered spells',description:'Fragile, but devastating at a distance.'},Ranger:{glyph:'↗',detail:'55 health · ranged attacks',description:'A steady bow and a watchful eye.'}};
function Dungeon({data,zoom}:{data:Snapshot;zoom:boolean}){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d')!;const tiles=data.tiles||town.tiles,p=data.me||{x:27,y:19},cols=zoom?45:35,rows=25,s=24,ox=Math.max(0,Math.min(W-cols,p.x-Math.floor(cols/2))),oy=Math.max(0,Math.min(H-rows,p.y-Math.floor(rows/2)));el.width=cols*s;el.height=rows*s;ctx.fillStyle='#090d0c';ctx.fillRect(0,0,el.width,el.height);ctx.font='17px monospace';ctx.textAlign='center';ctx.textBaseline='middle';const visible=new Set(data.visible||[]);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const gx=ox+x,gy=oy+y,t=tiles[gy]?.[gx]||' ',lit=!data.joined||visible.has(gy*W+gx);if(t===' ')continue;const px=x*s,py=y*s;ctx.globalAlpha=lit?1:.32;if(t==='#'){ctx.fillStyle='#25312b';ctx.fillRect(px+1,py+1,s-2,s-2);ctx.fillStyle='#394a3d';ctx.fillRect(px+1,py+1,s-2,2);ctx.fillStyle='#17251e';ctx.fillRect(px+2,py+s-3,s-3,2);}else{ctx.fillStyle=((gx+gy)%2)?'#111b17':'#131e19';ctx.fillRect(px,py,s,s);ctx.fillStyle='#2b3b2e';ctx.fillRect(px+11,py+12,2,2);if(t!=='.'){ctx.fillStyle=t==='>'||t==='<'?'#d4eeb0':t==='S'?'#d8bc76':'#90b7ad';ctx.fillText(t,px+12,py+13);}}}ctx.globalAlpha=1;
const draw=(x:number,y:number,glyph:string,color:string)=>{if(x<ox||y<oy||x>=ox+cols||y>=oy+rows)return;ctx.fillStyle=color;ctx.font='bold 21px monospace';ctx.fillText(glyph,(x-ox)*s+12,(y-oy)*s+13);};for(const l of data.loot||[])draw(l.x,l.y,l.kind==='gold'?'$':'!','#ddc77b');for(const m of data.monsters||[]){draw(m.x,m.y,m.glyph,m.color);if(m.hp<m.maxHp){ctx.fillStyle='#652f2b';ctx.fillRect((m.x-ox)*s+2,(m.y-oy)*s+23,20,2);ctx.fillStyle='#e88979';ctx.fillRect((m.x-ox)*s+2,(m.y-oy)*s+23,20*m.hp/m.maxHp,2);}}for(const q of data.players||[])draw(q.x,q.y,'@','#8fc7ed');if(data.me){const x=(p.x-ox)*s,y=(p.y-oy)*s;ctx.fillStyle='#a5d97920';ctx.fillRect(x,y,s,s);ctx.strokeStyle='#b8d58b';ctx.strokeRect(x+.5,y+.5,s-1,s-1);draw(p.x,p.y,'@','#e4ffc1');}else{draw(27,24,'@','#d3e5ad');} },[data,zoom]);return <canvas ref={canvas} className="dungeon" aria-label="Dungeon map. Your character is @. Use WASD or arrow keys to move."/>;}
export default function Home(){const [data,setData]=useState<Snapshot>({joined:false,online:0}),[name,setName]=useState(''),[role,setRole]=useState<keyof typeof classInfo>('Warrior'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connecting,setConnecting]=useState(true),[help,setHelp]=useState(false),[zoom,setZoom]=useState(false),[sound,setSound]=useState(false),[chat,setChat]=useState(''),[paused,setPaused]=useState(false);const state=useRef(data),inflight=useRef(false),audio=useRef<AudioContext|null>(null),keys=useRef(new Set<string>()),chatRef=useRef<HTMLInputElement>(null);state.current=data;
const beep=useCallback(()=>{if(!sound)return;try{audio.current??=new AudioContext();const c=audio.current,o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.setValueAtTime(180,c.currentTime);o.frequency.exponentialRampToValueAtTime(70,c.currentTime+.08);g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.13);}catch{}},[sound]);
const send=useCallback(async(action:Action)=>{while(inflight.current){if(action.type==='sync'||action.type==='move')return null;await new Promise(resolve=>setTimeout(resolve,25));}inflight.current=true;try{const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,id:Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('')}),signal:AbortSignal.timeout(10000)});const d=await r.json() as Snapshot & {error?:string};if(!r.ok)throw Error(d.error||'Unable to reach the realm.');setData(d);setError('');return d as Snapshot;}catch(e){setError((e as Error).message==='The operation was aborted due to timeout'?'Connection timed out. Reconnecting…':(e as Error).message);return null;}finally{inflight.current=false;setConnecting(false);}},[]);
const act=useCallback((type:string,extra:Partial<Action>={})=>{if(!state.current.joined||paused)return;if(type==='attack'||type==='spell')beep();void send({type,...extra});},[send,paused,beep]);
useEffect(()=>{if(paused)return;void send({type:'sync'});const timer=setInterval(()=>{if(!document.hidden)void send({type:'sync'});},500);return ()=>clearInterval(timer);},[send,paused]);
useEffect(()=>{const dirs:Record<string,[number,number]>={w:[0,-1],ArrowUp:[0,-1],s:[0,1],ArrowDown:[0,1],a:[-1,0],ArrowLeft:[-1,0],d:[1,0],ArrowRight:[1,0]};const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,[role="dialog"]'))return;if(e.key==='?'){setHelp(true);return;}if(help||!state.current.joined||paused)return;if(e.key==='Enter'){e.preventDefault();chatRef.current?.focus();return;}if(dirs[e.key]){e.preventDefault();keys.current.add(e.key);if(!e.repeat)act('move',{dx:dirs[e.key][0],dy:dirs[e.key][1]});}const actions:Record<string,string>={' ':'attack','1':'attack','2':'spell','3':'potion','4':'stairs',e:'stairs',q:'potion',r:'recall'};if(actions[e.key]&&!e.repeat){e.preventDefault();act(actions[e.key]);}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key);const blur=()=>keys.current.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);const t=setInterval(()=>{if(help||paused)return;const key=[...keys.current].at(-1);if(key&&dirs[key])act('move',{dx:dirs[key][0],dy:dirs[key][1]});},170);return()=>{clearInterval(t);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);keys.current.clear();};},[act,help,paused]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:Function}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'read_moria_character',description:'Read your current Moria character and visible nearby enemies.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({joined:state.current.joined,character:state.current.me,monsters:state.current.monsters})},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[]);
async function join(e:React.FormEvent){e.preventDefault();setBusy(true);setPaused(false);await send({type:'join',name,role});setBusy(false);}
async function leave(){const result=await send({type:'leave'});if(result){setPaused(true);keys.current.clear();}}
const p=data.me;
return <main className="shell"><header className="masthead"><div className="brand"><span className="brandmark">M</span><div><h1>MORIA <span>ONLINE</span></h1><p>THE SHARED DEEP</p></div></div><div className="realm-status"><span className={error?'status bad':'status'}/>{error?'Reconnecting':connecting?'Connecting':paused?'At rest':'Realm connected'}<span className="divider">/</span><Users size={15}/><span>{data.online} online</span></div><button className="icon-button" aria-label="How to play" onClick={()=>setHelp(true)}><HelpCircle size={19}/><span>Guide</span></button></header>
{error&&<div className="error" role="alert">{error} <button onClick={()=>void send({type:'sync'})}>Retry</button></div>}
<div className="game-layout"><section className="world-panel"><div className="world-heading"><div><span className="eyebrow">{p?`DEPTH ${String(p.floor).padStart(2,'0')} / ${p.floor*100} FT`:'A MULTIPLAYER DUNGEON'}</span><h2>{data.name||'Town of Stonehaven'}</h2></div><div className="world-tools"><span className="zone-tag">{p?.floor?'HOSTILE TERRITORY':'SANCTUARY'}</span><button aria-label="Toggle map zoom" className="icon-button" onClick={()=>setZoom(!zoom)}><Maximize2 size={17}/></button><button aria-label={sound?'Mute sounds':'Enable sounds'} className="icon-button" onClick={()=>setSound(!sound)}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}</button></div></div>
<div className="map-wrap"><Dungeon data={data} zoom={zoom}/><div className="map-caption"><span>{p?`X ${p.x} · Y ${p.y}`:'STONEHAVEN · THE SURFACE'}</span><span>{p?'@ YOU   @ ADVENTURERS':'EST. IN THE AGE OF ASCII'}</span></div>
{(!data.joined||paused)&&<div className="join-overlay"><form className="join-card" onSubmit={join}><span className="eyebrow">{paused?'YOUR JOURNEY IS SAVED':'ONE WORLD. MANY ADVENTURERS.'}</span><h2>{paused?'Return to the deep.':'The deep is calling.'}</h2><p>{paused?'Resume with your character, equipment, and progress.':'Descend together. Claim forgotten gold. Face what waits below.'}</p>{!paused&&<><label htmlFor="name">ADVENTURER NAME</label><input id="name" required minLength={2} maxLength={18} value={name} onChange={e=>setName(e.target.value)} placeholder="What shall they call you?" autoComplete="nickname"/><fieldset><legend>CHOOSE YOUR CLASS</legend><div className="class-options">{(Object.keys(classInfo) as (keyof typeof classInfo)[]).map(c=><label key={c} className={role===c?'class-option selected':'class-option'}><input type="radio" name="class" value={c} checked={role===c} onChange={()=>setRole(c)}/><strong>{classInfo[c].glyph}</strong><span>{c}</span></label>)}</div></fieldset><div className="class-description"><strong>{classInfo[role].detail}</strong><p>{classInfo[role].description}</p></div></>}<button className="enter-button" disabled={busy||connecting} type="submit">{busy?'Entering…':connecting?'Connecting…':paused?'Resume adventure':'Enter the realm'}<span>↗</span></button><small>Free to enter · Progress saved in this browser’s session</small></form></div>}
</div>
<div className="action-bar"><div className="actions">{[{type:'attack',key:'1',name:p?.role==='Ranger'?'Shoot':'Attack',Icon:Sword},{type:'spell',key:'2',name:'Arcane bolt',Icon:Flame},{type:'potion',key:'3',name:`Heal${p?` (${p.potions})`:''}`,Icon:FlaskConical},{type:'stairs',key:'E',name:'Use stairs',Icon:ArrowDownToLine}].map(({type,key,name,Icon})=><button key={type} disabled={!p||paused} onClick={()=>act(type)}><kbd>{key}</kbd><Icon size={20}/><span>{name}</span></button>)}</div><div className="movement-hint"><span><kbd>W</kbd><br/><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span><span>Move<br/><small>or arrow keys</small></span></div></div>
<div className="touch-controls"><button aria-label="Move left" onClick={()=>act('move',{dx:-1,dy:0})}><ChevronLeft/></button><button aria-label="Move up" onClick={()=>act('move',{dx:0,dy:-1})}><ChevronUp/></button><button aria-label="Move down" onClick={()=>act('move',{dx:0,dy:1})}><ChevronDown/></button><button aria-label="Move right" onClick={()=>act('move',{dx:1,dy:0})}><ChevronRight/></button></div>
<div className="bottom-panels"><section className="journal"><h3><ScrollText size={15}/> ADVENTURE LOG</h3><div className="log-lines" aria-live="polite">{p?p.log.slice(-4).map((l,i)=><p key={i} className={i===p.log.slice(-4).length-1?'latest':''}><span>›</span>{l}</p>):<><p><span>›</span>Beyond the town, the old stairs descend.</p><p><span>›</span>Five depths. One shared world.</p><p className="latest"><span>›</span>Your story has not been written yet.</p></>}</div></section><section className="chat"><h3><Users size={15}/> REALM CHAT</h3><div className="chat-lines">{data.chat?.length?data.chat.slice(-3).map((m,i)=><p key={i}><strong>{m.name}</strong> {m.text}</p>):<p className="quiet">A quiet moment before the next expedition.</p>}</div><form onSubmit={async e=>{e.preventDefault();if(!chat.trim())return;const r=await send({type:'chat',text:chat});if(r)setChat('');}}><input ref={chatRef} aria-label="Chat message" disabled={!p||paused} value={chat} onChange={e=>setChat(e.target.value)} maxLength={160} placeholder="Enter to chat…"/><button disabled={!p||paused} aria-label="Send chat message">↵</button></form></section></div>
</section>
<aside className="sidebar"><section className="character"><div className="section-label"><span>YOUR ADVENTURER</span><span className="small-symbol">✧</span></div><div className="character-name"><div className="avatar">@</div><div><h2>{p?.name||'Unwritten legend'}</h2><p>{p?`Level ${p.level} ${p.role}`:'Choose your path to begin'}</p></div></div><div className="stat"><span>HEALTH</span><strong>{p?`${p.hp} / ${p.maxHp}`:'— / —'}</strong></div><div className="meter health"><i style={{width:p?`${p.hp/p.maxHp*100}%`:'0%'}}/></div><div className="stat"><span>MANA</span><strong>{p?`${p.mp} / ${p.maxMp}`:'— / —'}</strong></div><div className="meter mana"><i style={{width:p?`${p.mp/p.maxMp*100}%`:'0%'}}/></div><div className="xp"><span>TO LEVEL {p?p.level+1:2}</span><span>{p?`${p.xp} / ${p.level*70}`:'0 / 70'} XP</span></div><div className="meter experience"><i style={{width:p?`${p.xp/(p.level*70)*100}%`:'0%'}}/></div><div className="currency"><span><Coins size={17}/> GOLD</span><strong>{p?.gold||0}<small>g</small></strong></div></section>
<Tabs defaultValue="pack" className="pack-tabs"><TabsList variant="line" className="tab-list"><TabsTrigger value="pack"><Backpack size={15}/> Pack</TabsTrigger><TabsTrigger value="realm"><Users size={15}/> Players</TabsTrigger></TabsList><TabsContent value="pack"><div className="inventory-row"><span className="item-icon"><Sword size={21}/></span><div><strong>{p?.role==='Mage'?'Ashwood staff':p?.role==='Ranger'?'Hunting bow':'Iron longsword'}</strong><small>Weapon · +{p?.weapon||0}</small></div></div><div className="inventory-row"><span className="item-icon"><Shield size={21}/></span><div><strong>Leather armor</strong><small>Defense · +{p?.armor||0}</small></div></div><div className="inventory-row"><span className="item-icon potion"><FlaskConical size={21}/></span><div><strong>Healing potion</strong><small>Restores 40 health</small></div><b>×{p?.potions??0}</b></div><button className="recall" disabled={!p||paused||!p.floor} onClick={()=>act('recall')}>Recall to town <span>10 g</span></button></TabsContent><TabsContent value="realm"><div className="roster">{data.roster?.length?data.roster.map(q=><div key={q.id}><span className="player-at">@</span><span><strong>{q.name}{q.id===p?.id?' (you)':''}</strong><small>Lv. {q.level} {q.role} · {q.floor?`${q.floor*100} ft`:'Town'}</small></span></div>):<p className="quiet">Enter the realm to meet other adventurers.</p>}</div></TabsContent></Tabs>
<section className="quest"><span className="eyebrow">THE DESCENT</span><h3>{p?.wins?'Conqueror of the deep':'A shadow beneath the mountain'}</h3><p>{p?.wins?'The Balrog has fallen by your hand. Help another adventurer find their way.':'Find the Balrog on the fifth depth. Bring a good blade. Better still, bring company.'}</p><div className="depth-track">{[1,2,3,4,5].map(d=><span className={p&&p.floor>=d?'reached':''} key={d}>{String(d).padStart(2,'0')}</span>)}</div></section>
{p&&<section className="trader"><h3>STONEHAVEN TRADER</h3>{p.floor?<p className="quiet">Return to town to trade.</p>:<>{[['potion','Healing potion',20],['weapon','Upgrade weapon',60*(p.weapon+1)],['armor','Upgrade armor',50*(p.armor+1)]].map(([item,label,cost])=><button key={item} disabled={paused||p.gold<Number(cost)} onClick={()=>act('buy',{item:String(item)})}>{label}<span>{cost} g</span></button>)}</>}</section>}
<div className="legend"><span><b className="you">@</b> You</span><span><b className="other">@</b> Player</span><span><b className="enemy">g</b> Monster</span><span><b>$</b> Gold</span><span><b>!</b> Potion</span><span><b>&gt;</b> Stairs</span></div>{p&&!paused&&<button className="leave" onClick={()=>void leave()}><LogOut size={15}/> Save & leave</button>}</aside></div>
<footer><span>MORIA ONLINE <b>·</b> A tribute to the original dungeon crawler</span><span>COOPERATIVE REALM <b>·</b> EARLY BUILD</span></footer>
<Dialog open={help} onOpenChange={setHelp}><DialogContent className="guide"><DialogHeader><DialogTitle>Surviving the deep</DialogTitle><DialogDescription>Shared adventure. Real-time danger. Your character keeps progressing while this guide is open.</DialogDescription></DialogHeader><dl>{[['WASD / Arrows','Move. Walk into adjacent monsters to attack.'],['Space / 1','Attack the nearest enemy. Rangers can shoot up to 4 tiles.'],['2','Arcane bolt. Costs 5 mana; reaches 6 tiles.'],['Q / 3','Drink a potion to recover 40 health.'],['E / 4','Use stairs while standing on < or >.'],['R','Recall to town for 10 gold.'],['Enter','Focus realm chat.']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>Loot is collected by walking over it. Nearby allies share kill experience. Town restores health; mana regenerates everywhere. Death returns you to town with 20% less gold.</p><p>Characters are saved on the server and recovered through a cookie in this browser. Use another browser or a private window for a second player. Logging out makes your character safe; closing the tab removes you after 15 seconds.</p></DialogContent></Dialog>
</main>;}
